import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import TagBar from "../components/TagBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="py-10 h-screen space-y-5 overflow-y-auto">
        <h1 className="font-bold text-3xl text-center">ችቦ</h1> 
          <div className="max-w-lg mx-auto bg-slate-100 rounded-md p-5 space-y-6">
            <NavBar />
            <TagBar />
            {children}
          </div>
      </div>  
        
     </body>
    </html>
  );
}
