apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchui-deployment
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: matchui-container
          image: your-docker-registry/matchui-app:latest  # Update with your Docker image
          ports:
            - containerPort: 80