apiVersion: v1
kind: Service
metadata:
  name: matchui-service
spec:
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Change to NodePort if using Minikube or ClusterIP if behind a load balancer